export enum TrafficSource {
  X = 'X',
  INSTAGRAM = 'INSTAGRAM',
  REFERRAL = 'REFERRAL',
  YOUTUBE = 'YOUTUBE',
  TIKTOK = 'TIKTOK',
  WHATSAPP = 'WHATSAPP',
  TELEGRAM = 'TELEGRAM',
  SEARCH_ENGINE = 'SEARCH_ENGINE',
  OTHERS = 'OTHERS',
}
